project:
  type: website

website:
  title: "Advanced Research Methods"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Introduction

bibliography: references.bib

format:
  html:
    theme: zephyr

  pdf:
    documentclass: scrreprt
    
  docx:
    toc: true



