project:
  type: website

website:
  title: "Advanced Research Methods"
  page-footer: 
    center:
      - text: "License"
        href: LICENSE.md
  navbar:
    navbar:
    search: true
    pinned: true
    left: 
      - href: home.qmd
        text: Home
      - href: 0_setup.qmd
        text: "Set-up steps"
      - text: "Weekly content"
        menu:
        - href: 1_intro.qmd
          text: "W1: Introduction"

format:
  html:
    theme: zephyr
    title-block-banner: true
    toc: true
    toc-location: left
    toc-title: "Outline"
    toc-depth: 2
    toc-expand: 2
    number-sections: true
    link-external-newwindow: true 

  pdf:
    documentclass: scrreprt
    papersize: a4
    fontfamily: "Verdana"
    geometry:
      - top=25mm
      - bottom=25mm
      - left=20mm
      - right=20mm
    
  docx:
    toc: true
    number-sections: true
    number-depth: 3
    page-width: 8.27